### ISSUE TITLE
Create map of OP population forecasts

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/BridgePk#12]
@sdiby As I mentioned, we received the population forecasts from the Office of Planning based on transportation analysis zones (TAZs). The data file (spreadsheet) and documentation are saved in **L:\Libraries\Planning\Raw\Forecasts**. 

Would like to ask you to please **create a map showing the population projections by TAZ ovelayed with the Bridge Park target area boundaries**. You should be able to download the TAZ shapefile from http://opendata.dc.gov/

This task may not require any actual coding. I'm using the GitHub issue as a work management tool in this case. We can use the chat feature for discussion, for instance. 

Please let me know if you have any questions. Thanks!

**Comment by ptatian** [comment]
@sdiby I got a TAZ shapefile from OP and placed it in **L:\Libraries\Planning\Maps**. According to OP, the data fields are as follows:

HH = Number of Households
HHPOP = Household Population
GQ = Group Quarters Population
TPOP = Total Population
EMP = Employment (Total Jobs)

Follow by YEAR 2010 through 2045 in five year increments.

**Comment by sdiby** [comment]
@ptatian great, thank you, Peter. I will take a look tomorrow.

**Comment by ptatian** [comment]
@sdiby They just sent me another version of the shapefile without the forecast data in it, in case that is more useful. **DC_TAZ3722.shp**

**Comment by ptatian** [comment]
@sdiby What is the status of this work? If it is ready to be reviewed, please issue a pull request and ask me for a review in the pull request comments. Thank you.

**Comment by ptatian** [comment]
Hi @sdiby. Just a reminder that we wanted to close up this issue. Was there any work that you needed to commit from this task?

**Comment by sdiby** [comment]
Thank you for the reminder @ptatian I'll take a look at this early next week to make sure I have no outstanding work, and close the issue.
