### ISSUE TITLE
Update Bridge Park Data Tables

### ISSUE THREAD

**Issue by jdev42092** [NeighborhoodInfoDC/BridgePk#2]
- [x] Add “Prepared by NeighborhoodInfo DC for 11th Street Bridge Park Equitable Development Plan Advisory Committee, June 5, 2017” to the footer of each page.
- [x] Add page numbers.
- [x] For tables showing percentages, add count data, too. The simplist thing would be to add the denominator as a row above the percentages. For example, number of persons 16 and older added above the labor force participation rate; number of persons in the labor force added above the unemployment rate, etc. 
- [x] For ACS 5-year data, use “2011-15” in the table title instead of “2015” only. 
- [x] For the number of assisted housing units table, can we add the number of rental units (numrenterhsgunits_2011_15) and the percentage assisted out of total rental units? 
- [x] For median sales prices, I prefer that we round to the nearest $100. 
- [x] Another useful couple of tables to have would be the numbers of single family homes and condo units (same time series). This can parallel the sales price/number of sales tables you have already. The data would come from the Realprop.Num_units_bpk data set using the units_condo_???? and units_sf_???? variables. 
- [x] Could also use a table showing basic population counts (totpop_????) and household counts (numoccupiedhsgunits_????) from 1990, 2000 and 2010. These would come from Ncdb.Ncdb_sum_bpk and Ncdb.Ncdb_sum_2010_bpk. 
- [x] Add list of data “in the works” after all of the tables.

**Comment by jdev42092** [comment]
> Another useful couple of tables to have would be the numbers of single family homes and condo units (same time series). This can parallel the sales price/number of sales tables you have already. The data would come from the Realprop.Num_units_bpk data set using the units_condo_???? and units_sf_???? variables.

@ptatian I take this to mean that we should split out the existing table of "Single Family and Condominium Units" by year into each separate category. Is that right?

**Comment by ptatian** [comment]
@jdev42092 Yes, that is correct. Sorry, I actually missed that we already had a unit count table. But, splitting the SF from condo units would make it more useful. Thank you!
