### ISSUE TITLE
Create population forecast maps for BP area using Planning data

### ISSUE THREAD

**Issue by sdiby** [NeighborhoodInfoDC/BridgePk#20]
- [x] Using OP forecast data, calculate percent change in population, households, and jobs between base years (2010 and 2015) and all other years (2020, 2025, 2030, 2035, 2040, 2045) for Census tracts within the Bridge Park geography
- [ ] Output corresponding shapefile
- [ ] Create map visualizing percent change in number of households between base year and 2045

**Comment by ptatian** [comment]
Hi @sdiby. Was any work done on this issue? I'd like to close it, since it doesn't seem that is needed anymore. But, if any work was done that we need to preserve then we should do a pull request. 

Please advise. Thanks!

**Comment by ptatian** [comment]
Hi @sdiby. Just checking again for your thoughts on this. Would like to close this issue but need to know if there's any work you need to commit and merge. Thanks.

**Comment by sdiby** [comment]
@ptatian thanks for your patience. Just submitted a pull request for this issue (develop-#19)

**Comment by sdiby** [comment]
@ptatian  branch (develop-#19) is merged and deleted, and program is synced and batch-submitted on L: without warnings or errors.

Log saved here: L:\Libraries\BridgePk\Prog\BPK Forecasts_2010-45.log
