### ISSUE TITLE
Update Bridge Park data tables

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/BridgePk#21]
This issue is for updating the standard Bridge Park data tables with the latest data in our warehouse. Should be started after the ACS 2013-17 updates are completed. We also processed new real property data since the last time we updated the tables. You can scan the Urban-Greater DC metadata (L:/Metadata/meta_updates.html) for any other updates we may want to include. 

@ocarena, I would like you to please work on this task with @sdiby's support and supervision. @sdiby, do we have any written instructions for this process? If not, perhaps we can make it part of this task to write out a simple set of steps to follow. 

Thank you.

**Comment by ptatian** [comment]
Hi @ocarena, I know things were very busy at the end of the year. Wanted to check in on this task to see if you have been able to make any progress.

**Comment by ocarena** [comment]
Hi, @ptatian Somala and I are meeting today to go over the steps. I have time in the next two days set aside to work on this.
