### ISSUE TITLE
Update Bridge Park summary data tables

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/BridgePk#25]
@ocarena This issue is for updating the Bridge Park data tables that we include with the annual update memo. The [previous update](https://github.com/NeighborhoodInfoDC/BridgePk/pull/19) involved modifying programs **Prog/BPK Summary Tabs.sas** and **Prog/BPK Summary Tabs_2012-16.sas**, but it seems like these programs do the same things so perhaps you can figure out which is the one that is most current. 

Data for the update should include

- [x] Latest ACS data (Rob just updated to 2014-18)
- [x] Real property through 2018
- [x] Crime data through 2018

In addition, we've added some new data that we may want to consider adding to the tables. Would you please look into these as well?

- [x] HMDA data (number of home purchase mortgages, median home purchase borrower income)
- [x] DCRA building permits
- [x] Vital stats number of births

Please let me or @rpitingolo know if you have any questions.

**Comment by mcohenui** [comment]
@ptatian Hey Peter, I was setting Olivia up to work on this update and looked through the metadata. I do not actually see the summary files for 2014-18 DC data. The ACS SF 5 year tables are up, but I do not think the summaries by geography are created yet. 

How should we proceed? Should we just run the ACS update too (https://github.com/NeighborhoodInfoDC/ACS/issues/158)? cc: @ocarena

**Comment by ptatian** [comment]
Hi @mcohenui. Thanks for flagging this. Yes, you can go ahead and complete that issue. Let me know if you have questions. @ocarena

**Comment by mcohenui** [comment]
@ocarena you are good to proceed on this. Let me know if you have questions about the process.

**Comment by ptatian** [comment]
Closing this issue. No related pull request.
