### ISSUE TITLE
Add ACS tabulations to EDPAC data tables

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/BridgePk#4]
@sdiby, here's the first assignment for the data work for the next EDPAC meeting. 

First, please review the [NIDC GitHub workflow](https://urbanorg.box.com/s/7tomkvi3o1vwxsv1dpg4oljes23m6y4x) . You can ask @rpitingolo or me if you have questions about it.

Add the following ACS summary tabulations to the EDPAC data tables (BPKPresentationResults.sas):
- [ ] Number of renter and homeowner households; homeownership rate (%)
- [ ] Number and percentage of renters with housing cost burden and severe housing cost burden 
- [ ] Number and percentage of homeowners with housing cost burden and severe housing cost burden
- [ ] Renter-occupied housing units by gross rent levels ($)
- [ ] Employed persons by major occupations
- [ ] Employed persons by major industries

You will first need to identify the appropriate ACS summary file tabulations for the above. A complete list of ACS tabulations can be found in L:\Libraries\ACS\Doc\SF_2011_15\ACS_2015_SF_5YR_Appendices.xls. If the tabulations above are not already in the latest NIDC ACS 2011-15 summary files, then we will need to open a new issue in the [ACS repo](https://github.com/NeighborhoodInfoDC/ACS/issues) to add those tabulations to the ACS summary files. 

Leah mentioned that the employed persons by occupations may already have been done for the equity project. 

Thanks! Let me know if you have any questions.

**Comment by ptatian** [comment]
@jdev42092, if you would please help @sdiby get oriented to the BPKPresentationResults.sas program and how it is used to update the tables, that would be great.

**Comment by lhendey** [comment]
@ptatian @sdiby @jdev42092 please coordinate with @rpitingolo - lily is supposed to move the variables created from the DC Equity project to the main ACS program.

**Comment by jdev42092** [comment]
@sdiby Happy to walk you through the process of updating the Bridge Park Tables. @rpitingolo Would you like to join a quick meeting on this?
