### ISSUE TITLE
Create Bridge Park parcel map - step 2

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/BridgePk#9]
@mcohenui, here are some suggested next steps on Bridge Park parcel map, building on work from issue #6. Please review and proceed as you see fit. If something turns out to be too hard, we can table for now. 

1. Incorporate condominium buildings into the current map (if not already there). 
2. [PADD properties](https://dhcd.dc.gov/sites/default/files/dc/sites/dhcd/publication/attachments/PADD%2520Acquisition%2520and%2520Disposition%2520Property%2520List%25204th%2520Quarter%25202016.pdf)
3. Bridge Park Community Land Trust properties (if available, need to ask Bridge Park) 
4. Federally-assisted housing (from Preservation Catalog). Can use PresCat.Parcel and/or PresCat.Parcel_subsidy data sets.
5. Potential rent-controlled properties. Dhcd.Parcels_rent_control (not in metadata, but on L:)
6. CAMA (property characteristics used for assessments). RealProp.camacommpt_2013_08, RealProp.camacondopt_2013_08, and RealProp.camarespt_2014_03. (Also not in metadata, but on L:)
7. Zoning designation. Need to download zoning shapefile from opendata.dc.gov and assign zoning characteristics to individual properties through a spatial join. 
8. Vacant property indicator. Should be available from OTR data (Parcel_base). Please see if there's something there we can easily include.

**Comment by ptatian** [comment]
@mcohenui Can I please get an update on where you are on the BP map?

**Comment by mcohenui** [comment]
@ptatian 

I have written the code to incorporate numbers 1, 4, 5, and 8. Here is my status on the others:

2. There is a PADD designation on the DC Owned Properties data set from Open Data DC which includes about 30 properties. The list of PADD properties from the PADD website has 161 (Many of these properties are in the DC Owned data set, just not labeled as PADD properties) Should I just use the list from PADD website?
3. Not sure if there are any CLT properties yet.
6. There is CAMA data on Open Data DC from 2017. Is there a reason to use the data from RealProp instead?
7. Still working on this piece in ArcMap

**Comment by ptatian** [comment]
Thanks, @mcohenui. 

2. I would use the list from the PADD web site. It's probably more current and complete.
3. Please ask Somala if we have any info on CLT properties.
4. No reason to use RealProp version instead of Open Data. It's really the same thing, except the version on Open Data may be more current. Just be aware there are (or were) different CAMA files that include different types of properties so you may need to join multiple files.

Would you please give me an estimate as to when we can have this completed? We need to close out the work for the current BP grant and transition to the next. Thanks!

**Comment by mcohenui** [comment]
@ptatian Thanks for the responses. I can wrap this up by the end of the week.

**Comment by ptatian** [comment]
@mcohenui Just documenting new source for PADD properties: https://octo.quickbase.com/db/bmt5bdteu?a=q&qid=6

**Comment by ptatian** [comment]
@mcohenui What is the status of this work? If it’s completed then please issue a pull request and ask me for a review in the comments. Thank you.

**Comment by ptatian** [comment]
@mcohenui Checking back on this. We need to close this issue. Is there work that you need to commit and merge?

**Comment by mcohenui** [comment]
@ptatian Thanks for the reminder, will commit and merge this week,
